language: rust
matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
    - rust: nightly
      script: cargo doc --no-deps
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        on:
          branch: master
script:
  - cargo build --verbose
  - cargo test --verbose
notifications:
  email:
    on_success: never
