name: CI
on: [push, pull_request]

jobs:
  wut:
    name: wut
    runs-on: ubuntu-latest
    steps:
      - run: cat /etc/issue
      - uses: docker://alpine:3.8
        with:
          args: cat /etc/issue
